### ISSUE TITLE
Suggestion For 	 Month - Open Source Calendar (Unreleased)  : Add the "Ring Tone Notification  " and "Drag And Drop  " features

### ISSUE THREAD

**Issue by nasirshah1813** [mauriceoegerli/Monthh#2]
![1.png](https://ipfs.busy.org/ipfs/QmUjJQ5wwsD9UGjWDpow7RjvMruzDuinTUKa3TpbEpksgF)

# Repository
https://github.com/mauriceoegerli/Monthh

# Components

Months - Open Source Calendar (Unreleased) is an open source calendar application. easily available on play store you can [download](https://play.google.com/store/apps/details?id=com.maurice.monthh) here. There are many features in this application like ( Month view.  Week, day & agenda view.
 Uses an Android calendar sync. Works with Google Calendar,  Free, open source, and absolutely no Ads)

Month - Open Source Calendar (Unreleased)  easy to use and all the design and features are very simple to understanding.

# Proposals

I like to suggest some features in this application.

#### 1-Ring Tone Notification

Many people miss the notification in this application because there is no sound of this notification.
with the help of this option, we can set Ring tone or Music on Event. When our Events/agenda  Will come near your time  The ringtone will start ringing in a loud voice  And in this way, we will not miss any notification. 

#### 2- Drag And Drop

Drag And Drop feature is very important for this application because when we want to move forward any agenda just simple  Drag your agenda and drop where you want. And in this way, you will not have to make a new agenda,  you can use the previous  agenda  In the coming date,
with the help of this button, you can also Drag And Drop
 any event.
One thing that you would surely love about drag-and-drop builder is the simplicity of the interface. Not only that, but it is also very easy to use especially if you want to edit or copy some events 

# Mockups/ Examples

![2.png](https://ipfs.busy.org/ipfs/QmeBAJQnH5iEVNoreqGpqQXYV72qTW1NtsB4VfsnGkXUnA)

![3.png](https://ipfs.busy.org/ipfs/QmbcNxPUXcxUNi994cUaGcFC9iwx8uevQEa8Y1J5og7X4s)

![4.png](https://ipfs.busy.org/ipfs/QmSev1jRUEhsH6Q59uHr4ytR2won5trRfNT41AgcwojCPf)

![5.png](https://ipfs.busy.org/ipfs/QmVq5PvCuHAxbidwLcizUAqLRSNRKmF8PgLF965Znmj4VH)

# Benefits

#### 1- Ring Tone Notification

1- You will receive the notification message as soon as possible
2- You will not miss any aven or agenda  notification
3- get a notification with  different sound 

#### 2- Drag And Drop

1-fastest way to move your agenda or even In the coming date,
2- easy to edit any agenda and events
3- Drag And Drop will Save your expensive time   

 # GitHub Account
https://github.com/nasirshah1813

**Comment by moisout** [comment]
Hi, thank you very much for your suggestions. Your feedback is very much appreciated, I am always excited about new Ideas.
I will look into it, and see if I can implement these features. You provided a very detailed description, which is really helpful.

**Comment by nasirshah1813** [comment]
Thank  u, sir, for  your feedback
